export const mealPlans = {
  // Haryana
  Faridabad: {
    breakfast: [
      "Besan Chilla with Mint Chutney",
      "Aloo Paratha with Curd",
      "Poha with Peanuts",
      "Vegetable Upma",
      "Stuffed Kulcha",
      "Masala Dosa with Coconut Chutney",
      "Poori Bhaji",
      "Idli Sambar",
      "Vegetable Sandwich",
      "Cornflakes with Milk and Fruits",
    ],
    lunch: [
      "Kadhi Pakora with Rice",
      "Mixed Dal with Bajra Roti",
      "Rajma Chawal",
      "Chole Bhature",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Palak Paneer with Rice",
      "Butter Chicken with Tandoori Roti",
      "Vegetable Kofta with Naan",
      "Chicken Biryani",
    ],
    dinner: [
      "Makki ki Roti with Sarson ka Saag",
      "Mixed Vegetable Curry with Phulka",
      "Paneer Butter Masala with Naan",
      "Dal Makhani with Jeera Rice",
      "Kadai Paneer with Tandoori Roti",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Roti with Aloo Gobi",
      "Malai Kofta with Naan",
      "Chicken Tikka Masala with Rice",
    ],
  },
  Gurgaon: {
    breakfast: [
      "Aloo Puri",
      "Moong Dal Cheela",
      "Vegetable Sandwich",
      "Idli Sambar",
      "Pav Bhaji",
      "Upma with Coconut Chutney",
      "Poha with Sev",
      "Masala Dosa",
      "Stuffed Paratha with Pickle",
      "Cornflakes with Milk and Fruits",
    ],
    lunch: [
      "Chicken Biryani",
      "Vegetable Kofta with Naan",
      "Palak Paneer with Rice",
      "Butter Chicken with Tandoori Roti",
      "Mixed Vegetable Curry with Phulka",
      "Rajma Chawal",
      "Kadhi Pakora with Rice",
      "Chole Bhature",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
    ],
    dinner: [
      "Rajma Chawal",
      "Kadhi Pakora with Rice",
      "Chole Bhature",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Dal Makhani with Jeera Rice",
      "Tandoori Chicken with Salad",
      "Vegetable Biryani",
      "Kadai Paneer with Tandoori Roti",
      "Malai Kofta with Naan",
    ],
  },
  // Punjab
  Amritsar: {
    breakfast: [
      "Amritsari Kulcha with Chole",
      "Aloo Paratha with Butter",
      "Pinni (Sweet Punjabi Dish)",
      "Poori Chole",
      "Lassi with Paratha",
      "Stuffed Kulcha with Chole",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
    ],
    lunch: [
      "Sarson ka Saag with Makki di Roti",
      "Amritsari Fish Fry with Naan",
      "Rajma Chawal",
      "Butter Chicken with Naan",
      "Chole Bhature",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Kadhi Pakora with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
    ],
    dinner: [
      "Dal Makhani with Jeera Rice",
      "Paneer Tikka Masala with Naan",
      "Tandoori Chicken with Salad",
      "Vegetable Biryani",
      "Kadai Paneer with Tandoori Roti",
      "Makki ki Roti with Sarson ka Saag",
      "Mixed Vegetable Curry with Phulka",
      "Paneer Butter Masala with Naan",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
    ],
  },
  Ludhiana: {
    breakfast: [
      "Stuffed Paratha with Curd",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Aloo Puri",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Rajma Chawal",
      "Kadhi Pakora with Rice",
      "Chole Bhature",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Butter Chicken with Tandoori Roti",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Vegetable Kofta with Naan",
    ],
    dinner: [
      "Makki ki Roti with Sarson ka Saag",
      "Mixed Vegetable Curry with Phulka",
      "Paneer Butter Masala with Naan",
      "Dal Makhani with Jeera Rice",
      "Kadai Paneer with Tandoori Roti",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  // Chandigarh
  Chandigarh: {
    breakfast: [
      "Aloo Paratha with Butter",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Stuffed Kulcha",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Rajma Chawal",
      "Kadhi Pakora with Rice",
      "Chole Bhature",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Butter Chicken with Tandoori Roti",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Vegetable Kofta with Naan",
    ],
    dinner: [
      "Makki ki Roti with Sarson ka Saag",
      "Mixed Vegetable Curry with Phulka",
      "Paneer Butter Masala with Naan",
      "Dal Makhani with Jeera Rice",
      "Kadai Paneer with Tandoori Roti",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  // Rajasthan
  Jaipur: {
    breakfast: [
      "Pyaaz Kachori",
      "Ghevar",
      "Dal Baati Churma",
      "Missi Roti",
      "Mohan Maas",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Laal Maas",
      "Gatte ki Sabzi",
      "Ker Sangri",
      "Bajre ki Roti with Lasun Chutney",
      "Dal Baati Churma",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Maas ke Sule",
      "Papad ki Sabzi",
      "Rajasthani Kadhi",
      "Bajra Khichdi",
      "Mawa Kachori",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Udaipur: {
    breakfast: [
      "Poha",
      "Mohan Maas",
      "Dal Baati Churma",
      "Missi Roti",
      "Ghevar",
      "Pyaaz Kachori",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Laal Maas",
      "Gatte ki Sabzi",
      "Ker Sangri",
      "Bajre ki Roti with Lasun Chutney",
      "Dal Baati Churma",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Maas ke Sule",
      "Papad ki Sabzi",
      "Rajasthani Kadhi",
      "Bajra Khichdi",
      "Mawa Kachori",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Jodhpur: {
    breakfast: [
      "Makhaniya Lassi",
      "Pyaaz Kachori",
      "Mawa Kachori",
      "Missi Roti",
      "Ghevar",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Laal Maas",
      "Gatte ki Sabzi",
      "Ker Sangri",
      "Bajre ki Roti with Lasun Chutney",
      "Dal Baati Churma",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Maas ke Sule",
      "Papad ki Sabzi",
      "Rajasthani Kadhi",
      "Bajra Khichdi",
      "Mawa Kachori",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Kota: {
    breakfast: [
      "Kota Kachori",
      "Dal Baati Churma",
      "Missi Roti",
      "Ghevar",
      "Mohan Maas",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Laal Maas",
      "Gatte ki Sabzi",
      "Ker Sangri",
      "Bajre ki Roti with Lasun Chutney",
      "Dal Baati Churma",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Maas ke Sule",
      "Papad ki Sabzi",
      "Rajasthani Kadhi",
      "Bajra Khichdi",
      "Mawa Kachori",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Ajmer: {
    breakfast: [
      "Pyaaz Kachori",
      "Ghevar",
      "Dal Baati Churma",
      "Missi Roti",
      "Mohan Maas",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Laal Maas",
      "Gatte ki Sabzi",
      "Ker Sangri",
      "Bajre ki Roti with Lasun Chutney",
      "Dal Baati Churma",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Maas ke Sule",
      "Papad ki Sabzi",
      "Rajasthani Kadhi",
      "Bajra Khichdi",
      "Mawa Kachori",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  // Maharashtra
  Mumbai: {
    breakfast: [
      "Vada Pav",
      "Poha",
      "Misal Pav",
      "Upma",
      "Sabudana Khichdi",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Pav Bhaji",
      "Bombay Biryani",
      "Fish Curry",
      "Vegetable Kolhapuri",
      "Chicken Tikka Masala",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Ragda Pattice",
      "Keema Pav",
      "Chicken Xacuti",
      "Malvani Fish Curry",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Pune: {
    breakfast: [
      "Misal Pav",
      "Poha",
      "Upma",
      "Sabudana Khichdi",
      "Vada Pav",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Pav Bhaji",
      "Bombay Biryani",
      "Fish Curry",
      "Vegetable Kolhapuri",
      "Chicken Tikka Masala",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Ragda Pattice",
      "Keema Pav",
      "Chicken Xacuti",
      "Malvani Fish Curry",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Nagpur: {
    breakfast: [
      "Saoji Chicken",
      "Poha",
      "Upma",
      "Sabudana Khichdi",
      "Vada Pav",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Pav Bhaji",
      "Bombay Biryani",
      "Fish Curry",
      "Vegetable Kolhapuri",
      "Chicken Tikka Masala",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Ragda Pattice",
      "Keema Pav",
      "Chicken Xacuti",
      "Malvani Fish Curry",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Nashik: {
    breakfast: [
      "Misal Pav",
      "Poha",
      "Upma",
      "Sabudana Khichdi",
      "Vada Pav",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Pav Bhaji",
      "Bombay Biryani",
      "Fish Curry",
      "Vegetable Kolhapuri",
      "Chicken Tikka Masala",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Ragda Pattice",
      "Keema Pav",
      "Chicken Xacuti",
      "Malvani Fish Curry",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Aurangabad: {
    breakfast: [
      "Misal Pav",
      "Poha",
      "Upma",
      "Sabudana Khichdi",
      "Vada Pav",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Pav Bhaji",
      "Bombay Biryani",
      "Fish Curry",
      "Vegetable Kolhapuri",
      "Chicken Tikka Masala",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Ragda Pattice",
      "Keema Pav",
      "Chicken Xacuti",
      "Malvani Fish Curry",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  // Delhi
  "New Delhi": {
    breakfast: [
      "Aloo Paratha with Butter",
      "Chole Bhature",
      "Poha",
      "Idli Sambar",
      "Stuffed Kulcha",
      "Poori Bhaji",
      "Masala Dosa",
      "Vegetable Sandwich",
      "Cornflakes with Milk and Fruits",
      "Upma with Coconut Chutney",
    ],
    lunch: [
      "Butter Chicken with Naan",
      "Rajma Chawal",
      "Chole Bhature",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Kadhi Pakora with Rice",
      "Vegetable Kofta with Naan",
    ],
    dinner: [
      "Dal Makhani with Jeera Rice",
      "Paneer Tikka Masala with Naan",
      "Tandoori Chicken with Salad",
      "Vegetable Biryani",
      "Kadai Paneer with Tandoori Roti",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
      "Chicken Tikka Masala with Rice",
      "Vegetable Pulao",
      "Mixed Vegetable Curry with Phulka",
    ],
  },
  // Uttar Pradesh
  Lucknow: {
    breakfast: [
      "Kachori Sabzi",
      "Poori Bhaji",
      "Jalebi with Rabri",
      "Stuffed Paratha",
      "Chole Bhature",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Lucknowi Biryani",
      "Galouti Kebab with Paratha",
      "Nihari with Kulcha",
      "Shami Kebab with Paratha",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Rogan Josh with Naan",
      "Kadai Paneer with Tandoori Roti",
      "Tandoori Chicken with Salad",
      "Vegetable Biryani",
      "Dal Makhani with Jeera Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
      "Chicken Tikka Masala with Rice",
      "Vegetable Pulao",
      "Mixed Vegetable Curry with Phulka",
    ],
  },
  Kanpur: {
    breakfast: [
      "Kachori Sabzi",
      "Poori Bhaji",
      "Jalebi with Rabri",
      "Stuffed Paratha",
      "Chole Bhature",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Lucknowi Biryani",
      "Galouti Kebab with Paratha",
      "Nihari with Kulcha",
      "Shami Kebab with Paratha",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Rogan Josh with Naan",
      "Kadai Paneer with Tandoori Roti",
      "Tandoori Chicken with Salad",
      "Vegetable Biryani",
      "Dal Makhani with Jeera Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
      "Chicken Tikka Masala with Rice",
      "Vegetable Pulao",
      "Mixed Vegetable Curry with Phulka",
    ],
  },
  Agra: {
    breakfast: [
      "Bedai with Aloo Sabzi",
      "Petha",
      "Kachori Sabzi",
      "Poori Bhaji",
      "Jalebi with Rabri",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Mughlai Paratha",
      "Tandoori Chicken with Naan",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Dal Makhani with Jeera Rice",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Kadhi Pakora with Rice",
      "Vegetable Kofta with Naan",
    ],
    dinner: [
      "Rogan Josh with Naan",
      "Kadai Paneer with Tandoori Roti",
      "Tandoori Chicken with Salad",
      "Vegetable Biryani",
      "Dal Makhani with Jeera Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
      "Chicken Tikka Masala with Rice",
      "Vegetable Pulao",
      "Mixed Vegetable Curry with Phulka",
    ],
  },
  Varanasi: {
    breakfast: [
      "Kachori Sabzi",
      "Poori Bhaji",
      "Jalebi with Rabri",
      "Stuffed Paratha",
      "Chole Bhature",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Banarasi Dum Aloo",
      "Baati Chokha",
      "Malaiyo",
      "Chena Dahi Vada",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Rogan Josh with Naan",
      "Kadai Paneer with Tandoori Roti",
      "Tandoori Chicken with Salad",
      "Vegetable Biryani",
      "Dal Makhani with Jeera Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
      "Chicken Tikka Masala with Rice",
      "Vegetable Pulao",
      "Mixed Vegetable Curry with Phulka",
    ],
  },
  Allahabad: {
    breakfast: [
      "Kachori Sabzi",
      "Poori Bhaji",
      "Jalebi with Rabri",
      "Stuffed Paratha",
      "Chole Bhature",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Lucknowi Biryani",
      "Galouti Kebab with Paratha",
      "Nihari with Kulcha",
      "Shami Kebab with Paratha",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Rogan Josh with Naan",
      "Kadai Paneer with Tandoori Roti",
      "Tandoori Chicken with Salad",
      "Vegetable Biryani",
      "Dal Makhani with Jeera Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
      "Chicken Tikka Masala with Rice",
      "Vegetable Pulao",
      "Mixed Vegetable Curry with Phulka",
    ],
  },
  // Gujarat
  Ahmedabad: {
    breakfast: [
      "Khaman Dhokla",
      "Thepla",
      "Fafda with Jalebi",
      "Handvo",
      "Poha",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Gujarati Thali",
      "Undhiyu with Puri",
      "Khandvi",
      "Dal Dhokli",
      "Methi Thepla",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Shrikhand with Puri",
      "Gujarati Kadhi with Rice",
      "Bhakhri with Shaak",
      "Patra",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Surat: {
    breakfast: [
      "Locho",
      "Khaman Dhokla",
      "Thepla",
      "Fafda with Jalebi",
      "Handvo",
      "Poha",
      "Idli Sambar",
      "Masala Dosa",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Gujarati Thali",
      "Undhiyu with Puri",
      "Khandvi",
      "Dal Dhokli",
      "Methi Thepla",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Shrikhand with Puri",
      "Gujarati Kadhi with Rice",
      "Bhakhri with Shaak",
      "Patra",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Vadodara: {
    breakfast: [
      "Khaman Dhokla",
      "Thepla",
      "Fafda with Jalebi",
      "Handvo",
      "Poha",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Gujarati Thali",
      "Undhiyu with Puri",
      "Khandvi",
      "Dal Dhokli",
      "Methi Thepla",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Shrikhand with Puri",
      "Gujarati Kadhi with Rice",
      "Bhakhri with Shaak",
      "Patra",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Rajkot: {
    breakfast: [
      "Khaman Dhokla",
      "Thepla",
      "Fafda with Jalebi",
      "Handvo",
      "Poha",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Gujarati Thali",
      "Undhiyu with Puri",
      "Khandvi",
      "Dal Dhokli",
      "Methi Thepla",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Shrikhand with Puri",
      "Gujarati Kadhi with Rice",
      "Bhakhri with Shaak",
      "Patra",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Bhavnagar: {
    breakfast: [
      "Khaman Dhokla",
      "Thepla",
      "Fafda with Jalebi",
      "Handvo",
      "Poha",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Gujarati Thali",
      "Undhiyu with Puri",
      "Khandvi",
      "Dal Dhokli",
      "Methi Thepla",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Shrikhand with Puri",
      "Gujarati Kadhi with Rice",
      "Bhakhri with Shaak",
      "Patra",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  // Tamil Nadu
  Chennai: {
    breakfast: [
      "Idli Sambar",
      "Dosa with Chutney",
      "Pongal",
      "Upma",
      "Vada",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Sambar Rice",
      "Rasam Rice",
      "Curd Rice",
      "Vegetable Biryani",
      "Chicken Chettinad",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Parotta with Kurma",
      "Fish Curry with Rice",
      "Chicken Biryani",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Coimbatore: {
    breakfast: [
      "Idli Sambar",
      "Dosa with Chutney",
      "Pongal",
      "Upma",
      "Vada",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Sambar Rice",
      "Rasam Rice",
      "Curd Rice",
      "Vegetable Biryani",
      "Chicken Chettinad",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Parotta with Kurma",
      "Fish Curry with Rice",
      "Chicken Biryani",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Madurai: {
    breakfast: [
      "Idli Sambar",
      "Dosa with Chutney",
      "Pongal",
      "Upma",
      "Vada",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Sambar Rice",
      "Rasam Rice",
      "Curd Rice",
      "Vegetable Biryani",
      "Chicken Chettinad",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Parotta with Kurma",
      "Fish Curry with Rice",
      "Chicken Biryani",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Tiruchirappalli: {
    breakfast: [
      "Idli Sambar",
      "Dosa with Chutney",
      "Pongal",
      "Upma",
      "Vada",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Sambar Rice",
      "Rasam Rice",
      "Curd Rice",
      "Vegetable Biryani",
      "Chicken Chettinad",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Parotta with Kurma",
      "Fish Curry with Rice",
      "Chicken Biryani",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Salem: {
    breakfast: [
      "Idli Sambar",
      "Dosa with Chutney",
      "Pongal",
      "Upma",
      "Vada",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Sambar Rice",
      "Rasam Rice",
      "Curd Rice",
      "Vegetable Biryani",
      "Chicken Chettinad",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Parotta with Kurma",
      "Fish Curry with Rice",
      "Chicken Biryani",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  // Karnataka
  Bengaluru: {
    breakfast: [
      "Idli Sambar",
      "Dosa with Chutney",
      "Pongal",
      "Upma",
      "Vada",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Bisi Bele Bath",
      "Ragi Mudde with Saaru",
      "Vegetable Biryani",
      "Chicken Chettinad",
      "Mysore Masala Dosa",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Neer Dosa with Chicken Curry",
      "Ragi Roti with Sambar",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Chicken Biryani",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Mysore: {
    breakfast: [
      "Idli Sambar",
      "Dosa with Chutney",
      "Pongal",
      "Upma",
      "Vada",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Bisi Bele Bath",
      "Ragi Mudde with Saaru",
      "Vegetable Biryani",
      "Chicken Chettinad",
      "Mysore Masala Dosa",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Neer Dosa with Chicken Curry",
      "Ragi Roti with Sambar",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Chicken Biryani",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Hubli: {
    breakfast: [
      "Idli Sambar",
      "Dosa with Chutney",
      "Pongal",
      "Upma",
      "Vada",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Bisi Bele Bath",
      "Ragi Mudde with Saaru",
      "Vegetable Biryani",
      "Chicken Chettinad",
      "Mysore Masala Dosa",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Neer Dosa with Chicken Curry",
      "Ragi Roti with Sambar",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Chicken Biryani",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Mangalore: {
    breakfast: [
      "Idli Sambar",
      "Dosa with Chutney",
      "Pongal",
      "Upma",
      "Vada",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Bisi Bele Bath",
      "Ragi Mudde with Saaru",
      "Vegetable Biryani",
      "Chicken Chettinad",
      "Mysore Masala Dosa",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Neer Dosa with Chicken Curry",
      "Ragi Roti with Sambar",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Chicken Biryani",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Belgaum: {
    breakfast: [
      "Idli Sambar",
      "Dosa with Chutney",
      "Pongal",
      "Upma",
      "Vada",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Bisi Bele Bath",
      "Ragi Mudde with Saaru",
      "Vegetable Biryani",
      "Chicken Chettinad",
      "Mysore Masala Dosa",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Neer Dosa with Chicken Curry",
      "Ragi Roti with Sambar",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Chicken Biryani",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  // West Bengal
  Kolkata: {
    breakfast: [
      "Luchi with Aloo Dum",
      "Poha",
      "Idli Sambar",
      "Upma",
      "Kathi Roll",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Macher Jhol with Rice",
      "Chingri Malai Curry",
      "Kosha Mangsho",
      "Vegetable Biryani",
      "Chicken Biryani",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
      "Chicken Tikka Masala with Rice",
    ],
    dinner: [
      "Roshogolla",
      "Mishti Doi",
      "Fish Curry with Rice",
      "Chicken Biryani",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Howrah: {
    breakfast: [
      "Luchi with Aloo Dum",
      "Poha",
      "Idli Sambar",
      "Upma",
      "Kathi Roll",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Macher Jhol with Rice",
      "Chingri Malai Curry",
      "Kosha Mangsho",
      "Vegetable Biryani",
      "Chicken Biryani",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
      "Chicken Tikka Masala with Rice",
    ],
    dinner: [
      "Roshogolla",
      "Mishti Doi",
      "Fish Curry with Rice",
      "Chicken Biryani",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Durgapur: {
    breakfast: [
      "Luchi with Aloo Dum",
      "Poha",
      "Idli Sambar",
      "Upma",
      "Kathi Roll",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Macher Jhol with Rice",
      "Chingri Malai Curry",
      "Kosha Mangsho",
      "Vegetable Biryani",
      "Chicken Biryani",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
      "Chicken Tikka Masala with Rice",
    ],
    dinner: [
      "Roshogolla",
      "Mishti Doi",
      "Fish Curry with Rice",
      "Chicken Biryani",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Asansol: {
    breakfast: [
      "Luchi with Aloo Dum",
      "Poha",
      "Idli Sambar",
      "Upma",
      "Kathi Roll",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Macher Jhol with Rice",
      "Chingri Malai Curry",
      "Kosha Mangsho",
      "Vegetable Biryani",
      "Chicken Biryani",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
      "Chicken Tikka Masala with Rice",
    ],
    dinner: [
      "Roshogolla",
      "Mishti Doi",
      "Fish Curry with Rice",
      "Chicken Biryani",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Siliguri: {
    breakfast: [
      "Luchi with Aloo Dum",
      "Poha",
      "Idli Sambar",
      "Upma",
      "Kathi Roll",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Macher Jhol with Rice",
      "Chingri Malai Curry",
      "Kosha Mangsho",
      "Vegetable Biryani",
      "Chicken Biryani",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
      "Chicken Tikka Masala with Rice",
    ],
    dinner: [
      "Roshogolla",
      "Mishti Doi",
      "Fish Curry with Rice",
      "Chicken Biryani",
      "Vegetable Pulao",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  // Haryana
  Panipat: {
    breakfast: [
      "Besan Chilla with Mint Chutney",
      "Aloo Paratha with Curd",
      "Poha with Peanuts",
      "Vegetable Upma",
      "Stuffed Kulcha",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Kadhi Pakora with Rice",
      "Mixed Dal with Bajra Roti",
      "Rajma Chawal",
      "Chole Bhature",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Makki ki Roti with Sarson ka Saag",
      "Mixed Vegetable Curry with Phulka",
      "Paneer Butter Masala with Naan",
      "Dal Makhani with Jeera Rice",
      "Kadai Paneer with Tandoori Roti",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Ambala: {
    breakfast: [
      "Besan Chilla with Mint Chutney",
      "Aloo Paratha with Curd",
      "Poha with Peanuts",
      "Vegetable Upma",
      "Stuffed Kulcha",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Kadhi Pakora with Rice",
      "Mixed Dal with Bajra Roti",
      "Rajma Chawal",
      "Chole Bhature",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Makki ki Roti with Sarson ka Saag",
      "Mixed Vegetable Curry with Phulka",
      "Paneer Butter Masala with Naan",
      "Dal Makhani with Jeera Rice",
      "Kadai Paneer with Tandoori Roti",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Karnal: {
    breakfast: [
      "Besan Chilla with Mint Chutney",
      "Aloo Paratha with Curd",
      "Poha with Peanuts",
      "Vegetable Upma",
      "Stuffed Kulcha",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Kadhi Pakora with Rice",
      "Mixed Dal with Bajra Roti",
      "Rajma Chawal",
      "Chole Bhature",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Makki ki Roti with Sarson ka Saag",
      "Mixed Vegetable Curry with Phulka",
      "Paneer Butter Masala with Naan",
      "Dal Makhani with Jeera Rice",
      "Kadai Paneer with Tandoori Roti",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  // Punjab
  Jalandhar: {
    breakfast: [
      "Amritsari Kulcha with Chole",
      "Aloo Paratha with Butter",
      "Pinni (Sweet Punjabi Dish)",
      "Poori Chole",
      "Lassi with Paratha",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Sarson ka Saag with Makki di Roti",
      "Amritsari Fish Fry with Naan",
      "Rajma Chawal",
      "Butter Chicken with Naan",
      "Chole Bhature",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Dal Makhani with Jeera Rice",
      "Paneer Tikka Masala with Naan",
      "Tandoori Chicken with Salad",
      "Vegetable Biryani",
      "Kadai Paneer with Tandoori Roti",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Patiala: {
    breakfast: [
      "Amritsari Kulcha with Chole",
      "Aloo Paratha with Butter",
      "Pinni (Sweet Punjabi Dish)",
      "Poori Chole",
      "Lassi with Paratha",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Sarson ka Saag with Makki di Roti",
      "Amritsari Fish Fry with Naan",
      "Rajma Chawal",
      "Butter Chicken with Naan",
      "Chole Bhature",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Dal Makhani with Jeera Rice",
      "Paneer Tikka Masala with Naan",
      "Tandoori Chicken with Salad",
      "Vegetable Biryani",
      "Kadai Paneer with Tandoori Roti",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  Bathinda: {
    breakfast: [
      "Amritsari Kulcha with Chole",
      "Aloo Paratha with Butter",
      "Pinni (Sweet Punjabi Dish)",
      "Poori Chole",
      "Lassi with Paratha",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Sarson ka Saag with Makki di Roti",
      "Amritsari Fish Fry with Naan",
      "Rajma Chawal",
      "Butter Chicken with Naan",
      "Chole Bhature",
      "Paneer Butter Masala with Naan",
      "Vegetable Pulao",
      "Chicken Biryani",
      "Mixed Vegetable Curry with Phulka",
      "Kadhi Pakora with Rice",
    ],
    dinner: [
      "Dal Makhani with Jeera Rice",
      "Paneer Tikka Masala with Naan",
      "Tandoori Chicken with Salad",
      "Vegetable Biryani",
      "Kadai Paneer with Tandoori Roti",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
  // Chandigarh
  Chandigarh: {
    breakfast: [
      "Aloo Paratha with Butter",
      "Poha with Peanuts",
      "Besan Chilla with Mint Chutney",
      "Vegetable Upma",
      "Stuffed Kulcha",
      "Idli Sambar",
      "Masala Dosa",
      "Poori Bhaji",
      "Cornflakes with Milk and Fruits",
      "Vegetable Sandwich",
    ],
    lunch: [
      "Rajma Chawal",
      "Kadhi Pakora with Rice",
      "Chole Bhature",
      "Vegetable Pulao",
      "Paneer Butter Masala with Naan",
      "Palak Paneer with Rice",
      "Mixed Vegetable Curry with Phulka",
      "Chicken Biryani",
      "Kadhi Pakora with Rice",
      "Vegetable Kofta with Naan",
    ],
    dinner: [
      "Makki ki Roti with Sarson ka Saag",
      "Mixed Vegetable Curry with Phulka",
      "Paneer Butter Masala with Naan",
      "Dal Makhani with Jeera Rice",
      "Kadai Paneer with Tandoori Roti",
      "Vegetable Biryani",
      "Tandoori Chicken with Salad",
      "Chicken Tikka Masala with Rice",
      "Malai Kofta with Naan",
      "Roti with Aloo Gobi",
    ],
  },
};
